backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/images
public_folder: /images

collections:
  - name: 'resume'
    label: 'Resume'
    folder: 'content/resume'
    format: 'frontmatter'
    create: true
    editor:
      preview: false
    widget: "text"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "about"}
      - {label: "About", name: "about", widget: "string"}
      - {label: "Document", name: "document", widget: "string"}
  - name: 'about'
    label: 'About'
    folder: 'content/about'
    format: 'frontmatter'
    create: true
    editor:
      preview: false
    widget: "select"      
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "about"}
      - {label: "About", name: "about", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'skills'
    label: 'Skills'
    folder: 'content/skill'
    format: 'frontmatter'
    create: true
    editor:
      preview: false
    widget: "select"      
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "skill"}
      - {label: "Skill", name: "skill", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
  - name: 'projects'
    label: 'Passion projects'
    folder: 'content/projects'
    format: 'frontmatter'
    create: true
    editor:
      preview: false
    widget: "select"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Cover", name: "cover", widget: "image"}
      - name: tech
        label: Tech
        widget: list
        fields:
          - {label: Tech1, name: tech1, widget: string}
          - {label: Tech2, name: tech2, widget: string}
          - {label: Tech3, name: tech3, widget: string}
          - {label: Tech4, name: tech4, widget: string}
          - {label: Tech5, name: tech5, widget: string}
      - name: features
        label: Features
        widget: list
        fields:
          - {label: Feature1, name: feature1, widget: string}
          - {label: Feature2, name: feature2, widget: string}
          - {label: Feature3, name: feature3, widget: string}
          - {label: Feature4, name: feature4, widget: string}
          - {label: Feature5, name: feature5, widget: string}          
          - {label: Feature6, name: feature6, widget: string}                    
      - {label: "Repo", name: "repo", widget: "string"}
      - {label: "Demo", name: "demo", widget: "string"}