backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/images
public_folder: /images

collections:
  - name: 'resume'
    label: 'Resume'
    folder: 'content/resume'
    format: 'frontmatter'
    create: true
    editor:
      preview: false
    widget: "text"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "about"}
      - {label: "About", name: "about", widget: "string"}
      - {label: "Document", name: "document", widget: "string"}
  - name: 'about'
    label: 'About'
    folder: 'content/about'
    format: 'frontmatter'
    create: true
    editor:
      preview: false
    widget: "select"      
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "about"}
      - {label: "About", name: "about", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'skills'
    label: 'Skills'
    folder: 'content/skill'
    format: 'frontmatter'
    create: true
    editor:
      preview: false
    widget: "select"      
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "skill"}
      - {label: "Skill", name: "skill", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
  - name: 'projects'
    label: 'Passion projects'
    folder: 'content/projects'
    format: 'frontmatter'
    create: true
    editor:
      preview: false
    widget: "select"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Cover", name: "cover", widget: "image"}
      - name: tech
        label: Tech
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
      - name: features
        label: Features
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Repo", name: "repo", widget: "string"}
      - {label: "Demo", name: "demo", widget: "string"}